### ISSUE TITLE
Youtube seems to be not working anymore.

### ISSUE THREAD

**Issue by purevertigo** [beardedspice/beardedspice#639]

**Comment by 1ps0** [comment]
details? 
Mac OSX version
Browser used and it's version
Bearded Spice version
Have you tried downloading updates?
Have you tried the wiki help for Safari?

**Comment by purevertigo** [comment]
Mac OS 10.12.4
Chrome 58
Bearded Spice 2.2.1
Yes
Not using Safari

thanks for the help.

**Comment by davidbucka** [comment]
Same problem and same versions

**Comment by 1ps0** [comment]
I was afraid of this. As per the Chrome Beta, it looks like they refactored some of the core functions for Chrome 58. Including the essential `executeJavascript:`

Looks like its gonna eat my weekend. Cheers.
More info as I have it.

**Comment by purevertigo** [comment]
Cheers

**Comment by 1ps0** [comment]
@purevertigo @tobylane Do a Compatibility Update. You should have the strategy for Synology v3.

This was quite an oversight and a new test case for the future. v2 of that strategy was breaking all the other strategies. Is fixed now.

**Comment by purevertigo** [comment]
Sorry, this doesn't seem fixed.

YouTube still not working. @1ps0

**Comment by tobylane** [comment]
Youtube, Soundcloud, Twitch not working in Chrome 58.0.3029.81 beta.

**Comment by 1ps0** [comment]
@tobylane please run Compatibility Updates and upgrade your Chrome (58) to stable. Betas are not supported.

@purevertigo can you do me a quick spotcheck? 
First, make sure that you grabbed the Synology v3 strategy.
Otherwise, do the following in a youtube tab:
1. kill Bearded Spice
2. refresh the tab
3. right click anywhere in the YT tab and select the 'inspect' menu option
4. go to the console tab. there should be a little 'no' button to clear the existing text
5. launch bearded spice
6. Observe any red errors appearing in the chrome console.

If you see anything, let me know. It could be the root of a similar issue. Easily fixable.
Otherwise, make sure that:
1. you have Accessibility enabled for BeardedSpice (System Preferences -> Security -> Privacy (tab) -> Accessibility (listed option) -> BeardedSpice.app is checked.
2. You're running the app out of the official `/Applications/` folder, not whereever the app was extracted from.

**Comment by purevertigo** [comment]
Nothing. Sorry. Still doesn't work and only getting errors about google ads. @1ps0 

Note - I have also been running beta on this particular machine since the start and have never had issues till now. Don't think it is a beta issue.

**Comment by 1ps0** [comment]
@tobylane @purevertigo I think I might have the answer. Take a look at https://github.com/beardedspice/beardedspice/releases/tag/v2.2.2-b1. If you can confirm that it fixes it for you, I'll hotfix in `2.2.2` official. Verification that it doesn't break El Capitan would be awesome too.

**Comment by purevertigo** [comment]
No @1ps0 sorry it doesn't fix it.

**Comment by drootstein** [comment]
Any chance you can release an official update so that Spotify works in the meantime?

**Comment by 1ps0** [comment]
@drootstein Yea, I'll be trying to get it out today. Vacation tomorrow :)

**Comment by 1ps0** [comment]
@drootstein and released. Please refer to the [build thread](https://github.com/beardedspice/beardedspice/issues/651) if you have any issues with it.

Thanks!

**Comment by pencilcheck** [comment]
The scan timeout is what makes me thought beardedspice wasn't working and after while it is just annoying because it is too slow, always have to wait for 10s to see video in youtube actually being played or paused.

At this current state, it is hard to say is useful especially for heavy power user like me who has usually 20+ to 100+ tabs opened at a time. Still appreciated the app though.

**Comment by 1ps0** [comment]
I've been trying to find an effective way to reduce that lag time, as I myself am also a heavy power user as you say. Theres a lot of low hanging fruit but I seem to be the only one who cares about reducing the technical debt that stands in the way. TBD.

**Comment by pencilcheck** [comment]
Why is there a 10s scan timeout? That doesn't sound right tbh. Reducing technical debt shouldn't be that hard as you should be able to comment, document and do it along development.

Btw, the project look a bit intimidating since it seems like there are nested xcode projects. I guess that's what you mean by reducing techncial debt?

**Comment by 1ps0** [comment]
It's not right but I moved it from 5 to 10s already, and I dont know/understand the motivation behind adding it, so I'm not removing it. For now. 

In the mean time I'm looking at the do-everything class of AppDelegate.m when I say tech debt, and the way the update scan is shoehorned in before every interaction. Lots to think about. 

Don't let the multiple projects scare you off, one is for the meat of it, another for the service that lets us capture the hotkeys. The last one is probably the normal cocoapod lib, just ignore that except to make sure it compiles ^_^

**Comment by pencilcheck** [comment]
Cool, but I still feel intimidated since it seems that I don't know what to focus on first and start small, it seems like the barrier to contribute is so high with so many moving parts (just my illusion but you can probably relate). If there is more in depth README and a simple example to get started that would help a lot. I would really like to make it work with beardedspice as I see this very useful but with this much delay, it is not viable.

**Comment by 1ps0** [comment]
I agree, the bar is far too high, and there are quite a lot of moving parts that require full knowledge of the system to really work with. One of my goals with my refactor is to properly document the featureset and the system architecture. It's fairly straight forward once you have a chance to see it laid out, but in its current form it might as well be gibberish. 

Unfortunately, at the moment my plate is full, but I do have a 80% refactor sitting around **[here](https://github.com/1ps0/beardedspice/pull/1)**. It's a work in progress but might give you a better idea of how things work together. Uh, it looks like I didn't commit my TODO, CHANGELOG, or other documentation (yet). When I have some breathing room I'll update it. 

The biggest slowdown is the ScriptingBridge interface and how we inject javascript. I have more revamp plans to make that a non-issue, but they're not committed at all, sorry.

**Comment by molerat619** [comment]
For me it's not working anymore since a few weeks. I was very happy before and hope I can use it again soon. I appreciate your work, thanks! 

Chrome: 68.0.x
MacOS: 10.13.6 
Bearded Spice: 2.2.3

**Comment by ayozemr** [comment]
Is there any updates on this?

**Comment by llaski** [comment]
@tobylane that worked for me, thanks!

**Comment by ayozemr** [comment]
Working for me too. Thanks!!
